name: Convert Markdown to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache texlive
        uses: actions/cache@v2
        with:
          path: /opt/texlive
          key: ${{ runner.os }}-texlive
          restore-keys: |
            ${{ runner.os }}-texlive

      - name: Cache pandoc
        uses: actions/cache@v2
        with:
          path: ~/.pandoc
          key: ${{ runner.os }}-pandoc
          restore-keys: |
            ${{ runner.os }}-pandoc

      - name: Install dependencies
        run: |
          sudo apt-get update
          if ! command -v pandoc &> /dev/null
          then
            sudo apt-get install -y pandoc
          fi
          if [ ! -d "/opt/texlive" ]; then
            sudo apt-get install -y texlive texlive-latex-extra
          fi

      - name: Convert draft.md to PDF with smaller margins and two columns
        run: |
          pandoc draft.md -o report.pdf --template=template.tex

      - name: Commit and push PDF
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B) && \
          git config --global user.name 'github-actions[bot]' && \
          git config --global user.email 'github-actions[bot]@users.noreply.github.com' && \
          git add report.pdf && \
          git commit -m "$LAST_COMMIT_MSG" && \
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
